{% set name = "plant" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/plant/plant/-/archive/v{{ version }}/plant-v{{ version }}.tar.gz
  sha256: 7ed05a3b018ce0a1a6827df7c878410ab5907ffa1abf521b1407eab05cc5c578

build:
  noarch: python
  entry_points:
    - plant_csv_reader = plant.app.plant_csv_reader:main
    - plant_display = plant.app.plant_display:main
    - plant_execute = plant.app.plant_execute:main
    - plant_filter = plant.app.plant_filter:main
    - plant_geocode = plant.app.plant_geocode:main
    - plant_info = plant.app.plant_info:main
    - plant_jaxafnf = plant.app.plant_jaxafnf:main
    - plant_ls = plant.app.plant_ls:main
    - plant_mosaic = plant.app.plant_mosaic:main
    - plant_radiometric_correction = plant.app.plant_radiometric_correction:main
    - plant_slantrange = plant.app.plant_slantrange:main
    - plant_util = plant.app.plant_util:main

  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:

  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip >=21.3

  run:
    - python >={{ python_min }}
    - setuptools
    - numpy >=2.0
    - poppler
    - gdal
    - h5py
    - matplotlib-base
    - scipy
    - pillow
    - jupyter
    - python-dateutil
    - numexpr

test:
  imports:
    - plant
  commands:
    - pip check
    - plant_info --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/plant/plant
  summary: PLANT is a collection of software tools developed at the Jet Propulsion Laboratory to support processing and analysis of Synthetic Aperture Radar (SAR) data for ecosystem and land-cover/land-use change science and applications.
  license: CC0-1.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gshiroma
