{% set name = "plant" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/plant/plant/-/archive/v{{ version }}/plant-v{{ version }}.tar.gz
  sha256: b0a5b747e51d3a14c1a56fa4b67b27b2a684aa9248e5e9ce7d90ee42ef5a0623

build:
  noarch: python
  entry_points:
    - plant_csv_reader = plant.app.plant_csv_reader:main_cli
    - plant_display = plant.app.plant_display:main_cli
    - plant_execute = plant.app.plant_execute:main_cli
    - plant_filter = plant.app.plant_filter:main_cli
    - plant_geocode = plant.app.plant_geocode:main_cli
    - plant_info = plant.app.plant_info:main_cli
    - plant_ls = plant.app.plant_ls:main_cli
    - plant_mosaic = plant.app.plant_mosaic:main_cli
    - plant_slantrange = plant.app.plant_slantrange:main_cli
    - plant_util = plant.app.plant_util:main_cli

  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:

  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip >=21.3

  run:
    - python >={{ python_min }}
    - setuptools
    - numpy >=1.25.2
    - poppler
    - gdal
    - h5py
    - matplotlib-base
    - scipy
    - pillow
    - jupyter
    - python-dateutil
    - numexpr

test:
  imports:
    - plant
  commands:
    - pip check
    - plant_info --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/plant/plant
  summary: PLANT is a collection of software tools developed at the Jet Propulsion Laboratory to support processing and analysis of Synthetic Aperture Radar (SAR) data for ecosystem and land-cover/land-use change science and applications.
  license: CC0-1.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gshiroma
